#1
a)

In [ ]:
import numpy as np
x=np.array([[6,7,4,7,8],[4,5,3,2,1],[5,6,8,9,0]])
a=x[1,1:4]
print(x)
print(a)


[[6 7 4 7 8]
 [4 5 3 2 1]
 [5 6 8 9 0]]
[5 3 2]


b)

In [ ]:
b=x[:,:3]
print(b)

[[6 7 4]
 [4 5 3]
 [5 6 8]]


c)

In [ ]:
c=x.T
print(c)

[[6 4 5]
 [7 5 6]
 [4 3 8]
 [7 2 9]
 [8 1 0]]


#2

In [ ]:
import numpy as np
a=np.arange(20,46)
print(a)
c=np.random.randint([25,46,3])
print(c)


[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45]
[23 16  0]


#3

In [ ]:
import numpy as np
a=np.zeros((10,10),dtype=int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


#4

In [ ]:
import  numpy as np
l1=[1,2,3,4,5,6,7,8]
a=np.array(l1)
print(a)
print("--------")
tuple1=([8,4,6],[1,2,3])
b=np.array(tuple1)
print(b)

[1 2 3 4 5 6 7 8]
--------
[[8 4 6]
 [1 2 3]]


#5

In [ ]:
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a[1,1,1]=0
print(a)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  0]]

 [[ 9 10]
  [11 12]]]


#6

In [ ]:
import numpy as np
a=np.array([1.1,1.2,1.3])
b=a.astype(int)
print(b)

[1 1 1]


#7

In [ ]:
import numpy as np
a=np.zeros((7,7),dtype=int)
a[1:6,1:6]=1
a[2:5,2:5]=2
a[3,3]=3
print(a)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 2 2 2 1 0]
 [0 1 2 3 2 1 0]
 [0 1 2 2 2 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


#8

In [ ]:
import numpy as np
a=np.array([[1,2],[4,6],[8,9],[2,2]])
b=a.T
print(b)


[[1 4 8 2]
 [2 6 9 2]]


#9
a)

In [ ]:
import numpy as np
a=np.array([[[5,6,7],[7,8,9],],[[0,4,8],[2,3,1]],[[9,5,3],[0,4,4]]])

a[:,1,1]=0
print(a)

[[[5 6 7]
  [7 0 9]]

 [[0 4 8]
  [2 0 1]]

 [[9 5 3]
  [0 0 4]]]


b)

In [ ]:
b=np.array([[[11,10,12],[88,0,45]],[[90,78,33],[41,77,0]],[[8,9,90],[12,67,9]]])
b[:,0,0::2]=0
print(b)

[[[ 0 10  0]
  [88  0 45]]

 [[ 0 78  0]
  [41 77  0]]

 [[ 0  9  0]
  [12 67  9]]]


#10

In [ ]:
import numpy as np
a=np.zeros((6,7),dtype=int)
a[:4:3,1::2]=1
a[2::3,::2]=1
print(a)



[[0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1]]
